AllCops:
  TargetRubyVersion: 2.3.5
  Exclude:
    - 'spec/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'sql_assess.gemspec'
    - 'Rakefile'

Metrics:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
